// data.js

export const taskData = {
    "TaskList": [
        {
            "RowNumber": 1,
            "TaskId": 1194,
            "Title": "Ok",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-31-2024 06:31:27 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-31-2024 04:01:32 PM",
            "CompletedDate": "10-31-2024 04:01:32 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-31-2024 04:01:32 PM",
            "CompletionPercentage": -1.00,
            "LeadName": null,
            "MobileNo": null,
            "LeadId": 0
        },
        {
            "RowNumber": 2,
            "TaskId": 1182,
            "Title": "vaibhav apraj : Make a Phone call",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-30-2024 10:31:00 AM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-29-2024 07:22:57 PM",
            "CompletedDate": "10-29-2024 07:22:57 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-29-2024 07:22:57 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "vaibhav apraj",
            "MobileNo": "09420150874",
            "LeadId": 1672
        },
        {
            "RowNumber": 3,
            "TaskId": 1181,
            "Title": "Test1 : Whatsapp",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-30-2024 04:21:00 AM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-29-2024 04:21:52 PM",
            "CompletedDate": "10-29-2024 04:21:52 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-29-2024 04:21:52 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Test1",
            "MobileNo": "",
            "LeadId": 1702
        },
        {
            "RowNumber": 4,
            "TaskId": 1183,
            "Title": "Saurabh12345 : Send Quotation",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-30-2024 02:51:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-30-2024 12:31:16 PM",
            "CompletedDate": "10-30-2024 12:31:16 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-29-2024 03:55:56 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 5,
            "TaskId": 1180,
            "Title": "Saurabh12345 : Send Quotation",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-30-2024 02:51:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-29-2024 03:44:22 PM",
            "CompletedDate": "10-29-2024 03:44:22 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-29-2024 03:43:56 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 6,
            "TaskId": 1179,
            "Title": "Saurabh12345 : Send Quotation",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-30-2024 02:51:00 PM",
            "Priority": "High",
            "TaskStatus": 0,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-29-2024 03:31:24 PM",
            "CompletedDate": "10-29-2024 03:31:24 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-29-2024 03:31:18 PM",
            "CompletionPercentage": 0.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 7,
            "TaskId": 1178,
            "Title": "Saurabh12345 : Send Quotation",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-30-2024 02:51:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-29-2024 02:47:39 PM",
            "CompletedDate": "10-29-2024 02:47:39 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-29-2024 02:47:39 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 8,
            "TaskId": 1176,
            "Title": "Saurabh12345 : This is use",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-29-2024 02:45:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-29-2024 02:41:50 PM",
            "CompletedDate": "10-29-2024 02:41:50 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-29-2024 02:41:50 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 9,
            "TaskId": 1175,
            "Title": "Saurabh12345 : Whatsapp",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-30-2024 02:45:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-29-2024 02:40:39 PM",
            "CompletedDate": "10-29-2024 02:40:39 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-29-2024 02:40:39 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 10,
            "TaskId": 1171,
            "Title": "Saurabh12345 : sdvb nn",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-29-2024 11:52:00 AM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-29-2024 11:29:16 AM",
            "CompletedDate": "10-29-2024 11:29:16 AM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-29-2024 11:29:16 AM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 11,
            "TaskId": 1169,
            "Title": "Saurabh12345 : Send Quotation",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-28-2024 06:13:00 AM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-28-2024 06:06:51 PM",
            "CompletedDate": "10-28-2024 06:06:51 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-28-2024 06:06:51 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 12,
            "TaskId": 1168,
            "Title": "Saurabh12345 : Whatsapp",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-28-2024 04:45:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-28-2024 04:39:22 PM",
            "CompletedDate": "10-28-2024 04:39:22 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-28-2024 04:39:22 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 13,
            "TaskId": 1167,
            "Title": "Saurabh12345 : Make a Phone call",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-28-2024 04:41:00 AM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-28-2024 04:37:04 PM",
            "CompletedDate": "10-28-2024 04:37:04 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-28-2024 04:37:04 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 14,
            "TaskId": 1166,
            "Title": "This Is Final Task By Sanjay",
            "Description": "fdsdfcgvbhgfds",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-28-2024 04:03:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-28-2024 03:58:14 PM",
            "CompletedDate": "10-28-2024 03:58:14 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-28-2024 03:58:14 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Saurabh12345",
            "MobileNo": "",
            "LeadId": 1708
        },
        {
            "RowNumber": 15,
            "TaskId": 1163,
            "Title": "Test1 : Email The Documents",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-28-2024 03:53:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-28-2024 03:49:18 PM",
            "CompletedDate": "10-28-2024 03:49:18 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-28-2024 03:49:18 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Test1",
            "MobileNo": "",
            "LeadId": 1702
        },
        {
            "RowNumber": 16,
            "TaskId": 1162,
            "Title": "Test1 : Email The Documents",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-29-2024 02:50:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-28-2024 02:51:47 PM",
            "CompletedDate": "10-28-2024 02:51:47 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-28-2024 02:51:47 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Test1",
            "MobileNo": "",
            "LeadId": 1702
        },
        {
            "RowNumber": 17,
            "TaskId": 1161,
            "Title": "Test1",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-29-2024 02:48:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-28-2024 02:49:29 PM",
            "CompletedDate": "10-28-2024 02:49:29 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-28-2024 02:49:29 PM",
            "CompletionPercentage": -1.00,
            "LeadName": null,
            "MobileNo": null,
            "LeadId": 0
        },
        {
            "RowNumber": 18,
            "TaskId": 1160,
            "Title": "Test1 : Make a Phone call",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-29-2024 02:42:00 PM",
            "Priority": "High",
            "TaskStatus": -1,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-28-2024 02:43:02 PM",
            "CompletedDate": "10-28-2024 02:43:02 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-28-2024 02:43:02 PM",
            "CompletionPercentage": -1.00,
            "LeadName": "Test1",
            "MobileNo": "",
            "LeadId": 1702
        },
        {
            "RowNumber": 19,
            "TaskId": 1142,
            "Title": "xsddffv ",
            "Description": "sddscdd",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-24-2024 12:00:00 AM",
            "Priority": "Low",
            "TaskStatus": 100,
            "MultimediaType": "",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-24-2024 12:21:29 PM",
            "CompletedDate": "10-24-2024 12:22:02 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-24-2024 12:21:29 PM",
            "CompletionPercentage": 100.00,
            "LeadName": "Test121",
            "MobileNo": "",
            "LeadId": 1706
        },
        {
            "RowNumber": 20,
            "TaskId": 1138,
            "Title": "Test1",
            "Description": "",
            "AssignedByUserId": 1248,
            "AssignedByUserName": "Rijo Varghese",
            "TaskEndDate": "10-23-2024 06:40:00 PM",
            "Priority": "High",
            "TaskStatus": 100,
            "MultimediaType": "T",
            "MultimediaName": "NA",
            "AssignedToUserId": 1248,
            "AssignedToUserName": "Rijo Varghese",
            "TaskCommentCount": 0,
            "CreateDate": "10-23-2024 06:36:46 PM",
            "CompletedDate": "10-24-2024 12:18:41 PM",
            "IsArchive": false,
            "Latitude": 0.000000,
            "Longitude": 0.000000,
            "Location": "",
            "IntercomGroupId": 0,
            "MultimediaModifiedDate": "10-23-2024 06:36:46 PM",
            "CompletionPercentage": 100.00,
            "LeadName": null,
            "MobileNo": null,
            "LeadId": 0
        }
    ]
  };
  